CREATE DATABASE IF NOT EXISTS GCS_CPP;

CREATE TABLE users (
    id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) DEFAULT 'user',
    token INT NOT NULL
);

CREATE TABLE history (
    id INT NOT NULL AUTOINCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);